services:
  - type: web
    name: democrac-server
    env: node
    plan: free
    branch: main
    buildCommand: npm install && cd server && npm install
    startCommand: cd server && node index.js
    rootDir: .
    envVars:
      - key: UPDATE_INTERVAL
        value: 300000
      - key: CORS_ORIGIN
        value: "*"
      - key: DB_PATH
        value: ./data/news.db

      - key: ADMIN_API_KEY
        sync: false
        value: YourSecretKeyHere123
      - key: AUTO_SUMMARIZE
        value: "true"
      - key: NODE_ENV
        value: "production"
