services:
  - type: web
    name: democrac-server
    env: node
    plan: free
    branch: main
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: UPDATE_INTERVAL
        value: 300000
      - key: CORS_ORIGIN
        value: "*"
      - key: DB_PATH
        value: ./data/news.db
      - key: GROQ_API_KEY
        value: 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
      - key: ADMIN_API_KEY
        value: YourSecretKeyHere123
