services:
  - type: web
    name: democrac-server
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: UPDATE_INTERVAL
        value: 300000
      - key: CORS_ORIGIN
        value: "*"
      - key: DB_PATH
        value: ./data/news.db
